[package]
name = "tt2-climb-the-tower"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
pathfinding = "4.14.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
